import { build } from "esbuild";
import { writeFile } from "node:fs/promises";
for (const name of ["recorder", "replayer"]) {
  const result = await build({
    entryPoints: [`src/runtime/${name}.ts`],
    bundle: true,
    write: false,
    format: "iife",
    platform: "browser",
    target: "es2022",
    minify: true,
    legalComments: "inline",
  });
  await writeFile(
    `src/${name}-bundle.ts`,
    `// Generated by scripts/build-runtime.mjs. Includes rrweb (MIT).\nexport const ${name}Bundle=${JSON.stringify(result.outputFiles[0].text)}\n`,
  );
}
