import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { DatabaseService } from '~/modules/database/database.service';
import { and, eq, not, sql } from 'drizzle-orm';
import { v4 as uuid } from 'uuid';
import * as schema from '#/models/schema';

type Status = 'pending' | 'started' | 'completed' | 'failed';
type Priority = 1 | 2 | 3 | 4 | 5;
const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export interface CreateGoalDto {
  agentId: string;
  sessionId?: string;
  title: string;
  description?: string;
  priority?: Priority;
  deadline?: Date | string;
  isAutoGenerated?: boolean;
  metadata?: Record<string, any>;
}

@Injectable()
export class GoalService {
  constructor(private readonly db: DatabaseService) {}

  private async requireAgentOwner(agentId: string, ownerId: string) {
    if (!ownerId || !agentId) throw new NotFoundException('Agent not found');
    const [row] = await this.db
      .select({ ownerUserId: schema.agent.ownerUserId, owner: schema.agent.owner })
      .from(schema.agent)
      .where(eq(schema.agent.agentId, agentId))
      .limit(1);
    if (
      !row ||
      ![row.ownerUserId, row.owner]
        .filter((value): value is string => Boolean(value))
        .some((value) => value.toLowerCase() === ownerId.toLowerCase())
    ) {
      throw new NotFoundException('Agent not found');
    }
  }

  async create(dto: CreateGoalDto, ownerId: string) {
    await this.requireAgentOwner(dto.agentId, ownerId);
    const title = dto.title?.trim();
    if (!title) throw new BadRequestException('A goal title is required');
    if (dto.priority !== undefined && ![1, 2, 3, 4, 5].includes(dto.priority)) {
      throw new BadRequestException('priority must be between 1 and 5');
    }
    const deadline = dto.deadline ? new Date(dto.deadline) : null;
    if (deadline && Number.isNaN(deadline.getTime())) {
      throw new BadRequestException('deadline must be a valid date');
    }
    const [row] = await this.db
      .insert(schema.goal)
      .values({
        goalId: uuid(),
        agentId: dto.agentId,
        sessionId: dto.sessionId ?? null,
        title,
        description: dto.description,
        priority: dto.priority ?? 2,
        deadline,
        status: 'pending',
        progress: 0,
        isAutoGenerated: dto.isAutoGenerated ?? false,
        metadata: dto.metadata,
      })
      .returning();
    return row;
  }
  //get next executable goal
  async getNextExecutableGoal(agentId: string) {
    const row = await this.db.query.goal.findFirst({
      where: (g: any) =>
        and(
          eq(g.agentId, agentId),
          not(eq(g.status, 'completed')),
          not(eq(g.status, 'failed')),
          eq(g.isAutoGenerated, false),
        ),
      orderBy: (g: any) => g.priority,
    });
    return row;
  }

  async recomputeProgress(goalId: string, ownerId: string) {
    await this.get(goalId, ownerId);
    const [{ value }] = await this.db
      .select({
        value: sql<number>`COALESCE(AVG(${schema.task.progress}),0)`,
      })
      .from(schema.task)
      .where(eq(schema.task.goalId, goalId));
    await this.db
      .update(schema.goal)
      .set({ progress: value, updatedAt: new Date() })
      .where(eq(schema.goal.goalId, goalId));
  }

  //update goal progress and status and completedAt if completed
  async updateProgress(goalId: string, progress: number, status: Status, ownerId: string) {
    await this.get(goalId, ownerId);
    if (!Number.isFinite(progress) || progress < 0 || progress > 100) {
      throw new BadRequestException('progress must be between 0 and 100');
    }
    if (!['pending', 'started', 'completed', 'failed'].includes(status)) {
      throw new BadRequestException('Invalid goal status');
    }
    const [row] = await this.db
      .update(schema.goal)
      .set({
        progress,
        status,
        updatedAt: new Date(),
        completedAt: status === 'completed' ? new Date() : null,
      })
      .where(eq(schema.goal.goalId, goalId))
      .returning();
    return row;
  }

  async get(goalId: string, ownerId: string) {
    if (!UUID_PATTERN.test(goalId)) throw new BadRequestException('Invalid goal ID');
    const row = await this.db.query.goal.findFirst({
      where: eq(schema.goal.goalId, goalId),
    });
    if (!row) throw new NotFoundException('Goal not found');
    await this.requireAgentOwner(row.agentId, ownerId);
    return row;
  }
}
