-- Native HubSpot CRM tools. Credentials are resolved from the initiating user.
INSERT INTO tool (tool_id, name, display_name, description, schema, api_spec, visibility, owner_type, category, tags, icon, version) VALUES
('55555555-5555-4555-8555-000000000001',
 'hubspot_search_contacts',
 'HubSpot: Search contacts',
 'Find HubSpot contacts by name or email. Read the returned record IDs before creating notes.',
 '{"type": "function", "function": {"name": "hubspot_search_contacts", "description": "Find HubSpot contacts by name or email. Read the returned record IDs before creating notes.", "parameters": {"type": "object", "required": ["query"], "properties": {"query": {"type": "string"}, "limit": {"type": "integer", "minimum": 1, "maximum": 100}}}}}'::jsonb,
 '{"baseUrl": "https://api.hubapi.com", "headers": {"Content-Type": "application/json"}, "authType": "oauth2", "oauthProviderKey": "hubspot", "path": "/crm/v3/objects/contacts/search", "method": "POST", "bodyTemplate": {"query": "{query}", "properties": ["firstname", "lastname", "email"], "limit": "{limit}"}, "oauthScopes": ["crm.objects.contacts.read"]}'::jsonb,
 'platform',
 'platform',
 'productivity',
 '["hubspot", "crm", "oauth2", "read"]'::jsonb,
 'users',
 '1.0.0'),
('55555555-5555-4555-8555-000000000002',
 'hubspot_create_contact',
 'HubSpot: Create contact',
 'Create a contact after the user approves its email and names. Set confirmed=true only after approval.',
 '{"type": "function", "function": {"name": "hubspot_create_contact", "description": "Create a contact after the user approves its email and names. Set confirmed=true only after approval.", "parameters": {"type": "object", "required": ["email", "confirmed"], "properties": {"email": {"type": "string"}, "firstName": {"type": "string"}, "lastName": {"type": "string"}, "confirmed": {"type": "boolean"}}}}}'::jsonb,
 '{"baseUrl": "https://api.hubapi.com", "headers": {"Content-Type": "application/json"}, "authType": "oauth2", "oauthProviderKey": "hubspot", "path": "/crm/v3/objects/contacts", "method": "POST", "bodyTemplate": {"properties": {"email": "{email}", "firstname": "{firstName}", "lastname": "{lastName}"}}, "oauthScopes": ["crm.objects.contacts.write"], "requiresConfirmation": true}'::jsonb,
 'platform',
 'platform',
 'productivity',
 '["hubspot", "crm", "oauth2", "write"]'::jsonb,
 'users',
 '1.0.0'),
('55555555-5555-4555-8555-000000000003',
 'hubspot_create_contact_note',
 'HubSpot: Create contact note',
 'Add an approved plain-text note to a contact ID returned by HubSpot. Set confirmed=true only after the user approves the contact and note.',
 '{"type": "function", "function": {"name": "hubspot_create_contact_note", "description": "Add an approved plain-text note to a contact ID returned by HubSpot. Set confirmed=true only after the user approves the contact and note.", "parameters": {"type": "object", "required": ["contactId", "note", "confirmed"], "properties": {"contactId": {"type": "string"}, "note": {"type": "string"}, "confirmed": {"type": "boolean"}}}}}'::jsonb,
 '{"baseUrl": "https://api.hubapi.com", "headers": {"Content-Type": "application/json"}, "authType": "oauth2", "oauthProviderKey": "hubspot", "path": "/crm/v3/objects/notes", "method": "POST", "bodyTransform": "hubspotContactNote", "oauthScopes": ["crm.objects.contacts.write"], "requiresConfirmation": true}'::jsonb,
 'platform',
 'platform',
 'productivity',
 '["hubspot", "crm", "oauth2", "write"]'::jsonb,
 'users',
 '1.0.0'),
('55555555-5555-4555-8555-000000000004',
 'hubspot_get_note',
 'HubSpot: Read note',
 'Read a saved HubSpot note by the ID returned from creation to verify its content.',
 '{"type": "function", "function": {"name": "hubspot_get_note", "description": "Read a saved HubSpot note by the ID returned from creation to verify its content.", "parameters": {"type": "object", "required": ["noteId"], "properties": {"noteId": {"type": "string"}}}}}'::jsonb,
 '{"baseUrl": "https://api.hubapi.com", "headers": {"Content-Type": "application/json"}, "authType": "oauth2", "oauthProviderKey": "hubspot", "path": "/crm/v3/objects/notes/{noteId}", "method": "GET", "queryParams": {"properties": "hs_note_body,hs_timestamp", "associations": "contacts"}, "oauthScopes": ["crm.objects.contacts.read"]}'::jsonb,
 'platform',
 'platform',
 'productivity',
 '["hubspot", "crm", "oauth2", "read"]'::jsonb,
 'users',
 '1.0.0')
ON CONFLICT (tool_id) DO UPDATE SET name=EXCLUDED.name, display_name=EXCLUDED.display_name, description=EXCLUDED.description, schema=EXCLUDED.schema, api_spec=EXCLUDED.api_spec, visibility=EXCLUDED.visibility, owner_type=EXCLUDED.owner_type, category=EXCLUDED.category, tags=EXCLUDED.tags, icon=EXCLUDED.icon, version=EXCLUDED.version, updated_at=timezone('utc', now());
