substitutions:
  _TAG: "default"
  _DEPLOY_TAG: ${BRANCH_NAME}

steps:
  - name: node
    dir: "./apps/commons-api"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        npm install -g pnpm
        pnpm install
        pnpm build

  - name: "gcr.io/cloud-builders/docker"
    dir: "./apps/commons-api"
    args:
      [
        "build",
        "-t",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/commons/commons-api:$SHORT_SHA",
        "-f",
        "Dockerfile",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    entrypoint: bash
    args:
      - -c
      - |
        TAG=$([ "$BRANCH_NAME" = "main" ] && echo "prod" || echo "$BRANCH_NAME")
        docker tag europe-west1-docker.pkg.dev/$PROJECT_ID/commons/commons-api:$SHORT_SHA \
                   europe-west1-docker.pkg.dev/$PROJECT_ID/commons/commons-api:$TAG

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/commons/commons-api",
        "--all-tags",
      ]

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: bash
    args:
      - -c
      - |
        DEPLOY_TAG=$([ "$BRANCH_NAME" = "main" ] && echo "prod" || echo "$BRANCH_NAME")
        gcloud run deploy arttribute-commons-api-$DEPLOY_TAG \
          --region=europe-west1 \
          --platform=managed \
          --image=europe-west1-docker.pkg.dev/$PROJECT_ID/commons/commons-api:$DEPLOY_TAG

    timeout: 1800s
# options:
#   machineType: "E2_MEDIUM"
