import { NextRequest, NextResponse } from "next/server";
import zlib from "node:zlib";
import { getAgentCommonsClient } from "@/lib/agent-commons";
import { normalizeCourseInput, type CourseInput } from "@/lib/course-input";
import { requireEducator, buildManagedCoursesFilter, slugifyCourseTitle } from "@/lib/educator-auth";
import { indexCourseForSearch } from "@/lib/search-indexers";
import Course from "@/models/Course";
import EducatorProfile from "@/models/EducatorProfile";
import type { SkillPack } from "@/types/skills";

type CopilotMode = "course" | "skill_path";

type MaterialExtract = {
  name: string;
  type: string;
  text: string;
  imageDataUrl?: string;
};

type CopilotDraft = {
  title?: string;
  tagline?: string;
  description?: string;
  longDescription?: string;
  duration?: string;
  level?: CourseInput["level"];
  modules?: NonNullable<CourseInput["modules"]>;
  skillPack?: SkillPack;
  notes?: string[];
};

const maxFiles = 8;
const maxTotalBytes = 18 * 1024 * 1024;
const maxTextChars = 22000;

export async function POST(req: NextRequest) {
  const authResult = await requireEducator();
  if (authResult.error) return authResult.error;

  const formData = await req.formData();
  const mode = normalizeMode(formData.get("mode"));
  const instructions = stringFormValue(formData.get("instructions")).slice(0, 4000);
  const targetCourseSlug = stringFormValue(formData.get("targetCourseSlug"));
  const files = formData
    .getAll("files")
    .filter((item): item is File => item instanceof File)
    .slice(0, maxFiles);

  if (!files.length) {
    return NextResponse.json(
      { error: "Upload at least one course material file." },
      { status: 400 }
    );
  }

  const totalBytes = files.reduce((sum, file) => sum + file.size, 0);
  if (totalBytes > maxTotalBytes) {
    return NextResponse.json(
      { error: "Uploaded materials must be smaller than 18 MB total." },
      { status: 400 }
    );
  }

  const materials = await Promise.all(files.map(extractMaterial));
  const materialText = materials
    .map((item) => `File: ${item.name}\n${item.text}`)
    .join("\n\n")
    .slice(0, maxTextChars);
  const images = materials.filter((item) => item.imageDataUrl).slice(0, 4);

  const draft = await createDraft({
    mode,
    instructions,
    materialText,
    images,
  });

  if (mode === "skill_path") {
    if (!targetCourseSlug) {
      return NextResponse.json(
        { error: "Choose a course for the generated skill path." },
        { status: 400 }
      );
    }
    const result = await createSkillPath({
      targetCourseSlug,
      draft,
      session: authResult.session,
    });
    if (result instanceof NextResponse) return result;
    return NextResponse.json(result, { status: 201 });
  }

  const result = await createCourse({
    draft,
    session: authResult.session,
  });
  if (result instanceof NextResponse) return result;
  return NextResponse.json(result, { status: 201 });
}

async function createCourse({
  draft,
  session,
}: {
  draft: CopilotDraft;
  session: NonNullable<Awaited<ReturnType<typeof requireEducator>>["session"]>;
}) {
  const profile = await EducatorProfile.findOne({ userId: session.userId });
  const title = cleanText(draft.title) || "AI-generated course draft";
  const slug = await uniqueCourseSlug(title);
  const skillPack = normalizeSkillPackDraft(draft.skillPack, title);
  const modules = normalizeModules(draft.modules, skillPack);
  const normalized = normalizeCourseInput({
    title,
    slug,
    tagline:
      cleanText(draft.tagline) ||
      "A practical CommonLab course generated from uploaded materials.",
    description:
      cleanText(draft.description) ||
      "A structured draft generated from uploaded course materials.",
    longDescription:
      toRichText(draft.longDescription) ||
      toRichText(draft.description) ||
      "<p>This draft was generated by the CommonLab educator copilot. Review, edit, and publish when ready.</p>",
    duration: cleanText(draft.duration) || "Self-paced",
    level: draft.level || "beginner",
    price: 0,
    isFree: true,
    courseType: "self-paced",
    modules,
    skillPacks: [skillPack],
    published: false,
  });

  const course = await Course.create({
    ...normalized,
    slug,
    instructor: profile?.displayName || "CommonLab educator",
    educator: {
      userId: session.userId,
      name: profile?.displayName,
      plan: profile?.plan || "free",
      settlementMode: profile?.settlementMode || "platform_rails",
      platformFeePercent: profile?.platformFeePercent ?? 20,
      paystackSubaccountCode: profile?.paystackSubaccountCode,
      stripeAccountId: profile?.stripeAccountId,
    },
  });
  await indexCourseForSearch(course);

  return {
    mode: "course",
    course: {
      title: course.title,
      slug: course.slug,
      href: `/educator/courses/${course.slug}/edit`,
    },
    skillPath: {
      title: skillPack.title,
      slug: skillPack.slug,
      href: `/skills/${skillPack.slug}`,
    },
    notes: draft.notes || [],
  };
}

async function createSkillPath({
  targetCourseSlug,
  draft,
  session,
}: {
  targetCourseSlug: string;
  draft: CopilotDraft;
  session: NonNullable<Awaited<ReturnType<typeof requireEducator>>["session"]>;
}) {
  const filter =
    session.role === "admin"
      ? { slug: targetCourseSlug }
      : {
          slug: targetCourseSlug,
          ...buildManagedCoursesFilter({
            userId: session.userId,
            email: session.email,
            role: session.role,
          }),
        };
  const course = await Course.findOne(filter);
  if (!course) {
    return NextResponse.json(
      { error: "Course not found or you do not manage it." },
      { status: 404 }
    );
  }

  const skillPack = normalizeSkillPackDraft(draft.skillPack, course.title);
  const currentPacks = (Array.isArray(course.skillPacks)
    ? course.skillPacks
    : []) as SkillPack[];
  const nextPacks = [
    ...currentPacks.filter((pack) => pack?.slug !== skillPack.slug),
    skillPack,
  ];
  const courseModule = moduleFromSkillPack(skillPack);
  const currentModules = (Array.isArray(course.modules)
    ? course.modules
    : []) as ReturnType<typeof moduleFromSkillPack>[];
  const nextModules = [
    ...currentModules.filter((item) => item?.title !== courseModule.title),
    courseModule,
  ];

  course.set({
    skillPacks: nextPacks,
    modules: nextModules,
    modulesCount: nextModules.length,
    lessonsCount: nextModules.reduce(
      (sum, item) => sum + (item.lessons?.length || 0),
      0
    ),
  });
  await course.save();
  await indexCourseForSearch(course);

  return {
    mode: "skill_path",
    course: {
      title: course.title,
      slug: course.slug,
      href: `/educator/courses/${course.slug}/skills`,
    },
    skillPath: {
      title: skillPack.title,
      slug: skillPack.slug,
      href: `/skills/${skillPack.slug}`,
    },
    notes: draft.notes || [],
  };
}

async function createDraft(input: {
  mode: CopilotMode;
  instructions: string;
  materialText: string;
  images: MaterialExtract[];
}): Promise<CopilotDraft> {
  const agentDraft = await draftWithAgentCommons(input);
  if (agentDraft) return agentDraft;

  const openAiDraft = await draftWithOpenAI(input);
  if (openAiDraft) return openAiDraft;

  return fallbackDraft(input);
}

async function draftWithAgentCommons(input: {
  mode: CopilotMode;
  instructions: string;
  materialText: string;
}) {
  const client = getAgentCommonsClient();
  const agentId = process.env.EDUCATOR_COPILOT_AGENT_ID;
  if (!client || !agentId || !input.materialText.trim()) return null;

  try {
    const result = await client.run.once({
      agentId,
      messages: [
        {
          role: "system",
          content: copilotSystemPrompt(),
        },
        {
          role: "user",
          content: JSON.stringify({
            mode: input.mode,
            educatorInstructions: input.instructions,
            materialText: input.materialText,
          }),
        },
      ],
    });
    return normalizeDraftJson(extractText(result), input);
  } catch {
    return null;
  }
}

async function draftWithOpenAI(input: {
  mode: CopilotMode;
  instructions: string;
  materialText: string;
  images: MaterialExtract[];
}) {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) return null;

  try {
    const content: Array<
      | { type: "text"; text: string }
      | { type: "image_url"; image_url: { url: string } }
    > = [
      {
        type: "text",
        text: JSON.stringify({
          mode: input.mode,
          educatorInstructions: input.instructions,
          materialText: input.materialText,
          outputShape:
            "Return JSON with title, tagline, description, longDescription, duration, level, modules, skillPack, and notes. Skill challenges usually need lesson HTML, keyIdeas, and 2 quiz questions. Pure orientation or introduction challenges may have 0 quiz questions. If an introduction is combined with the first substantive concept, quiz only the taught concept, not the orientation. Keep each challenge focused on one main concept.",
        }),
      },
      ...input.images.map((image) => ({
        type: "image_url" as const,
        image_url: { url: image.imageDataUrl || "" },
      })),
    ];

    const response = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: process.env.EDUCATOR_COPILOT_MODEL || "gpt-4o-mini",
        temperature: 0.25,
        response_format: { type: "json_object" },
        messages: [
          { role: "system", content: copilotSystemPrompt() },
          { role: "user", content },
        ],
      }),
    });
    if (!response.ok) return null;
    const payload = (await response.json()) as {
      choices?: Array<{ message?: { content?: string } }>;
    };
    return normalizeDraftJson(payload.choices?.[0]?.message?.content || "", input);
  } catch {
    return null;
  }
}

function copilotSystemPrompt() {
  return [
    "You are the CommonLab educator course copilot.",
    "Create rigorous, accessible course material from uploaded educator materials.",
    "Match the source material closely. Do not introduce concepts that are not supported by the material or educator instructions.",
    "Respect learner intelligence: make ideas clear without dumbing them down, avoid filler repetition, and use consistent terminology.",
    "Pace the learning carefully. Introduce one main concept at a time, then build on it.",
    "Do not announce the teaching strategy in learner-facing text. Do not write phrases like 'at a steady pace' or 'one concept at a time' in the course content; make the structure itself do that work.",
    "Use clean, simple sentence structure while keeping field-specific technical terms.",
    "Use clear titles that stand on their own. Avoid ambiguous labels such as 'Components' when 'Workflow Components' is the accurate term.",
    "Use standard learning design: short introductions, meaningful examples, key ideas, challenging quizzes, and practical sandbox tasks when relevant.",
    "Do not force a quiz on a pure introduction or orientation. A short intro can also be combined with the first substantive concept when that creates a smoother learning path.",
    "Return only valid JSON.",
  ].join("\n");
}

function normalizeDraftJson(text: string, input: { mode: CopilotMode; materialText: string }) {
  if (!text.trim()) return null;
  try {
    const parsed = JSON.parse(text) as CopilotDraft;
    return {
      ...parsed,
      skillPack: normalizeSkillPackDraft(parsed.skillPack, parsed.title || "Generated skill path"),
      modules: normalizeModules(parsed.modules, parsed.skillPack),
    };
  } catch {
    return fallbackDraft(input);
  }
}

function fallbackDraft(input: { mode: CopilotMode; materialText: string }) {
  const title =
    firstLikelyTitle(input.materialText) ||
    (input.mode === "skill_path" ? "Generated Skill Path" : "Generated Course Draft");
  const skillPack = normalizeSkillPackDraft(
    {
      enabled: true,
      title: input.mode === "skill_path" ? title : `${title}: Skill Path`,
      subtitle: "Generated from uploaded course material.",
      learnerPromise:
        "Learners will review the core ideas, check understanding, and complete a focused practice task.",
      challenges: fallbackChallenges(input.materialText),
    },
    title
  );

  return {
    title,
    tagline: "A practical draft generated from uploaded materials.",
    description: "Review and edit this AI-generated draft before publishing.",
    longDescription:
      "This course draft was generated from uploaded material. The educator should review lesson accuracy, examples, quiz challenge level, and sandbox scope before publishing.",
    duration: "Self-paced",
    level: "beginner",
    modules: normalizeModules(undefined, skillPack),
    skillPack,
    notes: [
      "The copilot used a deterministic fallback because no AI generation provider returned a draft.",
      input.materialText.trim()
        ? "Review the draft against the uploaded material before publishing."
        : "No extractable text was found. Upload text files or slide images for stronger results.",
    ],
  } satisfies CopilotDraft;
}

function fallbackChallenges(materialText: string): SkillPack["challenges"] {
  const topics = extractTopicLines(materialText).slice(0, 4);
  const safeTopics = topics.length ? topics : ["Core idea", "Key example", "Practice task"];
  return safeTopics.map((topic, index) => ({
    id: slugifyCourseTitle(topic) || `challenge-${index + 1}`,
    day: index + 1,
    title: topic,
    shortTitle: topic.slice(0, 32),
    minutes: index === safeTopics.length - 1 ? 12 : 7,
    points: index === safeTopics.length - 1 ? 110 : 70,
    streakBoost: 1,
    accentColor: ["#8BE7F0", "#86EFAC", "#FDE047", "#FDBA74"][index % 4],
    audioCue: index === safeTopics.length - 1 ? "complete" : "focus",
    hook: `Focus on ${topic.toLowerCase()} and explain why it matters.`,
    lesson: toRichText(
      `Start by identifying what the source material says about ${topic}. Then connect the idea to a concrete learner task. Keep the explanation clear, specific, and grounded in the provided material.`
    ),
    keyIdeas: [
      `Define ${topic}.`,
      "Connect the idea to a practical example.",
      "Check the learner can apply the idea.",
    ],
    microTask: `Write one practical use of ${topic.toLowerCase()}.`,
    questions: [
      {
        id: "q1",
        prompt: `What should a strong explanation of ${topic} do?`,
        options: [
          "Stay grounded in the source material and use a practical example",
          "Introduce unrelated concepts before the learner has context",
          "Avoid checking whether the learner can apply the idea",
          "Use different terms for the same idea without explanation",
        ],
        answerIndex: 0,
        explanation:
          "Good course material stays grounded, consistent, and applicable.",
      },
      {
        id: "q2",
        prompt: "What should the educator do before publishing this generated draft?",
        options: [
          "Review accuracy, examples, quiz choices, and task scope",
          "Publish without reading it",
          "Remove all quiz feedback",
          "Add unsupported topics to make it longer",
        ],
        answerIndex: 0,
        explanation:
          "Generated course material should be reviewed before learners see it.",
      },
    ],
  }));
}

function normalizeSkillPackDraft(input: SkillPack | undefined, fallbackTitle: string): SkillPack {
  const title = cleanText(input?.title) || `${fallbackTitle} Skill Path`;
  const slug = slugifyCourseTitle(input?.slug || title) || "generated-skill-path";
  const challenges = Array.isArray(input?.challenges) ? input.challenges : [];
  const normalizedChallenges = challenges
    .map((challenge, index) => ({
      id: cleanText(challenge.id) || `challenge-${index + 1}`,
      day:
        typeof challenge.day === "number" && challenge.day > 0
          ? Math.floor(challenge.day)
          : index + 1,
      title: cleanText(challenge.title) || `Challenge ${index + 1}`,
      shortTitle: cleanText(challenge.shortTitle) || undefined,
      minutes:
        typeof challenge.minutes === "number" && challenge.minutes > 0
          ? Math.floor(challenge.minutes)
          : 7,
      points:
        typeof challenge.points === "number" && challenge.points > 0
          ? Math.floor(challenge.points)
          : 70,
      streakBoost:
        typeof challenge.streakBoost === "number" && challenge.streakBoost >= 0
          ? Math.floor(challenge.streakBoost)
          : 1,
      assetUrl: cleanText(challenge.assetUrl) || undefined,
      assetAlt: cleanText(challenge.assetAlt) || undefined,
      accentColor: cleanText(challenge.accentColor) || "#8BE7F0",
      audioCue: ["spark", "focus", "complete"].includes(challenge.audioCue || "")
        ? challenge.audioCue
        : "focus",
      hook: cleanText(challenge.hook) || undefined,
      lesson: toRichText(challenge.lesson) || "<p>Lesson draft coming soon.</p>",
      keyIdeas: Array.isArray(challenge.keyIdeas)
        ? challenge.keyIdeas.map(cleanText).filter(Boolean).slice(0, 5)
        : [],
      microTask: cleanText(challenge.microTask) || undefined,
      practicalSignal: challenge.practicalSignal,
      sandbox: challenge.sandbox,
      questions: Array.isArray(challenge.questions)
        ? challenge.questions
            .map((question, questionIndex) => ({
              id: cleanText(question.id) || `q${questionIndex + 1}`,
              prompt: cleanText(question.prompt) || "",
              options: Array.isArray(question.options)
                ? question.options.map(cleanText).filter(Boolean).slice(0, 5)
                : [],
              answerIndex:
                typeof question.answerIndex === "number"
                  ? Math.max(0, Math.floor(question.answerIndex))
                  : 0,
              explanation: cleanText(question.explanation) || undefined,
            }))
            .filter(
              (question) =>
                question.prompt &&
                question.options.length >= 2 &&
                question.answerIndex < question.options.length
            )
        : [],
    }))
    .map((challenge, index) => ({
      ...challenge,
      questions:
        challenge.sandbox?.enabled ||
        challenge.questions.length ||
        isOrientationOnlyChallenge(challenge, index)
          ? challenge.questions
          : defaultQuestions(challenge.title),
    }))
    .filter((challenge) => challenge.title && challenge.lesson)
    .slice(0, 8);

  return {
    slug,
    enabled: true,
    title,
    subtitle: cleanText(input?.subtitle) || "Generated from uploaded course material.",
    coverUrl: cleanText(input?.coverUrl) || undefined,
    learnerPromise:
      toRichText(input?.learnerPromise) ||
      "Learners will understand the key ideas and practice applying them.",
    challenges: normalizedChallenges.length
      ? normalizedChallenges
      : fallbackChallenges("").slice(0, 3),
  };
}

function isOrientationOnlyChallenge(
  challenge: Pick<
    SkillPack["challenges"][number],
    "title" | "shortTitle" | "hook" | "lesson"
  >,
  index: number
) {
  if (index !== 0) return false;
  const title = `${challenge.title || ""} ${challenge.shortTitle || ""}`.toLowerCase();
  const text = `${title} ${challenge.hook || ""} ${challenge.lesson || ""}`.toLowerCase();
  const hasIntroTitle =
    /\b(intro|introduction|orientation|overview|welcome|map)\b/.test(title) ||
    title.includes("what makes") ||
    title.includes("start here") ||
    title.includes("getting started");
  const hasConceptTitle =
    /\b(scheduled|routine|cron|workflow|components?|trigger|node|edge|memory|computer|workspace|sandbox)\b/.test(
      title
    );
  return !hasConceptTitle && (hasIntroTitle || text.includes("this path"));
}

function defaultQuestions(topic: string): SkillPack["challenges"][number]["questions"] {
  return [
    {
      id: "q1",
      prompt: `What is the strongest way to learn ${topic}?`,
      options: [
        "Connect the idea to the source material and apply it in a practical task",
        "Memorize isolated words without checking meaning",
        "Skip examples because they slow down learning",
        "Use unrelated terms before they are introduced",
      ],
      answerIndex: 0,
      explanation:
        "Strong learning connects the idea to the source and then asks the learner to use it.",
    },
    {
      id: "q2",
      prompt: "What should an educator review before publishing AI-generated material?",
      options: [
        "Accuracy, terminology, examples, quiz choices, and task scope",
        "Only the title",
        "Only the button color",
        "Nothing, because generated drafts are automatically final",
      ],
      answerIndex: 0,
      explanation:
        "Educators should review generated drafts before learners use them.",
    },
  ];
}

function normalizeModules(
  modules: CopilotDraft["modules"] | undefined,
  skillPack?: SkillPack
) {
  const normalized = Array.isArray(modules)
    ? modules
        .map((module, index) => ({
          title: cleanText(module.title) || `Module ${index + 1}`,
          description: toRichText(module.description) || undefined,
          assignment: toRichText(module.assignment) || undefined,
          lessons: Array.isArray(module.lessons)
            ? module.lessons
                .map((lesson, lessonIndex) => ({
                  title: cleanText(lesson.title) || `Lesson ${lessonIndex + 1}`,
                  duration: cleanText(lesson.duration) || "10",
                  description: toRichText(lesson.description) || undefined,
                  assetUrl: cleanText(lesson.assetUrl) || undefined,
                  assetAlt: cleanText(lesson.assetAlt) || undefined,
                  isFree: Boolean(lesson.isFree),
                }))
                .filter((lesson) => lesson.title)
            : [],
        }))
        .filter((module) => module.title && module.lessons.length)
    : [];
  if (normalized.length) return normalized;
  return skillPack ? [moduleFromSkillPack(skillPack)] : [];
}

function moduleFromSkillPack(skillPack: SkillPack) {
  return {
    title: skillPack.title,
    description:
      toRichText(skillPack.learnerPromise) ||
      "<p>Practice the skill path through focused lessons and checks.</p>",
    lessons: skillPack.challenges.map((challenge) => ({
      title: challenge.title,
      duration: String(challenge.minutes || 7),
      description: challenge.lesson,
      assetUrl: challenge.assetUrl,
      assetAlt: challenge.assetAlt,
      isFree: challenge.day === 1,
    })),
  };
}

async function extractMaterial(file: File): Promise<MaterialExtract> {
  const buffer = Buffer.from(await file.arrayBuffer());
  const type = file.type || guessMimeType(file.name);

  if (type.startsWith("image/")) {
    return {
      name: file.name,
      type,
      text: `Image uploaded: ${file.name}`,
      imageDataUrl: `data:${type};base64,${buffer.toString("base64")}`,
    };
  }

  if (type === "application/pdf" || file.name.toLowerCase().endsWith(".pdf")) {
    const text = extractLoosePdfText(buffer);
    return {
      name: file.name,
      type,
      text:
        text ||
        "PDF uploaded, but no extractable text was found. If this PDF is image-only, upload slide images as well for stronger AI drafting.",
    };
  }

  if (
    type.startsWith("text/") ||
    /\.(md|markdown|txt|csv|json)$/i.test(file.name)
  ) {
    return {
      name: file.name,
      type,
      text: buffer.toString("utf8").slice(0, maxTextChars),
    };
  }

  return {
    name: file.name,
    type,
    text: `Uploaded unsupported file type ${type}. Use text, PDF, or image files for best results.`,
  };
}

function extractLoosePdfText(buffer: Buffer) {
  const raw = buffer.toString("latin1");
  const chunks = [raw];
  let offset = 0;
  while (true) {
    const streamIndex = raw.indexOf("stream", offset);
    if (streamIndex === -1) break;
    const endIndex = raw.indexOf("endstream", streamIndex);
    if (endIndex === -1) break;
    const header = raw.slice(Math.max(0, streamIndex - 400), streamIndex);
    if (header.includes("FlateDecode")) {
      let start = streamIndex + "stream".length;
      if (raw[start] === "\r" && raw[start + 1] === "\n") start += 2;
      else if (raw[start] === "\n") start += 1;
      let end = endIndex;
      while (end > start && (raw[end - 1] === "\n" || raw[end - 1] === "\r")) end -= 1;
      try {
        chunks.push(zlib.inflateSync(buffer.subarray(start, end)).toString("utf8"));
      } catch {
        // Ignore compressed streams that are not text streams.
      }
    }
    offset = endIndex + "endstream".length;
  }

  const text = chunks
    .flatMap((chunk) => extractPdfStrings(chunk))
    .join("\n")
    .replace(/[^\S\r\n]+/g, " ")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
  return text.slice(0, maxTextChars);
}

function extractPdfStrings(value: string) {
  const matches = value.match(/\((?:\\.|[^\\)]){2,}\)/g) || [];
  return matches
    .map((item) =>
      item
        .slice(1, -1)
        .replace(/\\n/g, "\n")
        .replace(/\\r/g, "\n")
        .replace(/\\t/g, " ")
        .replace(/\\([()\\])/g, "$1")
    )
    .filter((item) => /[A-Za-z]{3}/.test(item))
    .slice(0, 600);
}

async function uniqueCourseSlug(title: string) {
  const base = slugifyCourseTitle(title) || "course-draft";
  let slug = base;
  for (let index = 2; index < 100; index += 1) {
    const existing = await Course.exists({ slug });
    if (!existing) return slug;
    slug = `${base}-${index}`;
  }
  return `${base}-${Date.now()}`;
}

function normalizeMode(value: FormDataEntryValue | null): CopilotMode {
  return value === "skill_path" ? "skill_path" : "course";
}

function stringFormValue(value: FormDataEntryValue | null) {
  return typeof value === "string" ? value.trim() : "";
}

function cleanText(value: unknown) {
  return typeof value === "string" ? value.trim() : "";
}

function toRichText(value: unknown) {
  const text = cleanText(value);
  if (!text) return "";
  if (/<\/?[a-z][\s\S]*>/i.test(text)) return text;
  return text
    .split(/\n{2,}/)
    .map((paragraph) => paragraph.trim())
    .filter(Boolean)
    .map((paragraph) => `<p>${paragraph}</p>`)
    .join("");
}

function extractText(value: unknown): string {
  if (!value) return "";
  if (typeof value === "string") return value;
  if (Array.isArray(value)) return value.map(extractText).filter(Boolean).join("\n");
  if (typeof value === "object") {
    const record = value as Record<string, unknown>;
    for (const key of ["content", "message", "text", "output", "response", "final"]) {
      const text = extractText(record[key]);
      if (text) return text;
    }
  }
  return "";
}

function firstLikelyTitle(text: string) {
  return (
    text
      .split(/\r?\n/)
      .map((line) => line.replace(/^#+\s*/, "").trim())
      .find((line) => line.length >= 6 && line.length <= 80) || ""
  );
}

function extractTopicLines(text: string) {
  return Array.from(
    new Set(
      text
        .split(/\r?\n/)
        .map((line) => line.replace(/^[-*#\d.\s]+/, "").trim())
        .filter((line) => line.length >= 5 && line.length <= 64)
    )
  );
}

function guessMimeType(name: string) {
  if (/\.pdf$/i.test(name)) return "application/pdf";
  if (/\.(png|jpg|jpeg|webp)$/i.test(name)) return "image/*";
  if (/\.(md|markdown|txt|csv|json)$/i.test(name)) return "text/plain";
  return "application/octet-stream";
}
