export function html(nonce: string, source: string, css: string, js: string): string {
  return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src ${source}; script-src 'nonce-${nonce}'; img-src ${source} data:;">
<link href="${css}" rel="stylesheet"><title>Agent Commons</title></head><body>
<header class="topbar"><button class="title" id="home" title="Show chat"><span class="brand">◇</span><span id="title">Commons</span></button><nav aria-label="Chat navigation"><button class="icon" id="history-toggle" title="Chat history" aria-label="Chat history" data-icon="history"></button><button class="icon" id="account-toggle" title="Account" aria-label="Account" data-icon="user"></button><button class="icon" data-action="start" title="New chat" aria-label="New chat" data-icon="compose"></button></nav></header>
<main id="main">
<section id="welcome" class="welcome"><span class="welcome-mark" aria-hidden="true">◇</span><h1>A little help.<br>A lot of possibility.</h1><p>Your agents, right beside your code.</p><div id="signin"><button class="primary wide" data-action="login">Continue with Commons <span aria-hidden="true">↗</span></button><p class="small">Sign in securely in your browser.</p></div><div id="device" hidden><p>Enter this code in your browser</p><strong id="device-code"></strong><button class="primary wide" data-action="reopenLogin">Open sign-in page ↗</button><button class="text" data-action="stop">Cancel sign-in</button></div></section>
<section id="chat" hidden><div id="recent"></div><div id="empty" class="empty"><span class="welcome-mark" aria-hidden="true">◇</span><h1>What are we building?</h1><p>Explore an idea. Fix a bug. Make it yours.</p><div class="suggestions"><button data-prompt="Explore this project and explain how it works.">Explore this project <span>↗</span></button><button data-action="review">Review current code <span>↗</span></button></div></div><div id="messages" role="log" aria-label="Conversation"></div><div id="working" class="working" role="status" hidden><span class="pulse"></span> Working…</div></section>
<section id="history" class="panel" hidden><div class="panel-heading"><h2>Chats</h2><button class="icon" data-action="refresh" aria-label="Refresh history" title="Refresh history" data-icon="refresh"></button></div><input id="search" type="search" placeholder="Search your chats…" aria-label="Search chats"><div class="filters"><button id="all-filter" class="active">All chats</button><button id="local-filter">This project</button></div><div id="session-list"></div></section>
<section id="account" class="panel" hidden><h2>Your account</h2><div class="account-card"><div class="avatar" id="avatar">C</div><strong id="account-name"></strong><span id="account-email" class="muted"></span><span id="account-workspace" class="small"></span></div><div class="menu-list"><button data-action="manageAccount">Manage account <span>↗</span></button><button data-action="selectAgent">Choose an agent <span>↗</span></button><button data-action="settings">Extension settings <span>↗</span></button><button data-action="logout">Sign out <span>↗</span></button></div><p class="small">Your Commons account is shared with the CLI on this machine.</p></section>
</main>
<div id="feedback" role="status" aria-live="polite" hidden></div>
<div id="approval" class="approval" hidden><strong id="approval-title">Review action</strong><details><summary>View details</summary><pre id="approval-detail"></pre></details><div class="approval-actions"><button id="deny">Decline</button><button id="allow" class="primary">Allow once</button></div></div>
<div id="composer-area" hidden><form id="composer"><div id="attachments" class="chips"></div><textarea id="prompt" rows="2" maxlength="100000" aria-label="Message your agent" placeholder="Ask Commons to build something…"></textarea><div class="composer-footer"><div class="composer-tools"><div class="add-wrap"><button type="button" id="add" class="icon" title="Add context" aria-label="Add context" aria-expanded="false" data-icon="plus"></button><div id="add-menu" class="popover" hidden><button type="button" data-action="attach">Attach files <span>↗</span></button><button type="button" data-action="attachEditor">Current file or selection <span>↗</span></button></div></div><select id="mode" aria-label="Local tool permissions" title="Local tool permissions"><option value="ask">Ask before edits</option><option value="read-only">Read only</option><option value="off">Tools off</option></select></div><button type="button" id="agent" class="agent" data-action="selectAgent" title="Choose agent">Default agent</button><button id="send" class="send" type="submit" aria-label="Send message" title="Send message" data-icon="arrow"></button></div></form><div class="workspace-footer"><span data-icon="folder" aria-hidden="true"></span><span id="folder">Your project</span><span class="keyboard-hint">↵ send · ⇧↵ newline</span></div></div>
<script nonce="${nonce}" src="${js}"></script></body></html>`;
}
